### ISSUE TITLE
Can't cast from desktop Chrome browser (Google Cast or DIAL protocol?)

### ISSUE THREAD

**Issue by mmortal03** [yuliskov/SmartTubeNext#403]
I just tested 10.81. While it is possible to link an Android phone's YouTube app with the code, casting YouTube videos from a Chrome-based desktop browser such as Google Chrome and Microsoft Edge does not work. It worked in SmartYouTubeTV. I'm not sure if this is technically Google Cast or the DIAL protocol, but it worked in SmartYouTubeTV, and doesn't work in SmartTubeNext.

**Comment by Frozenlock** [comment]
I would upvote this issue a hundred times if I could!
I'm constantly casting from my PC and having the "built-in" youtube app launch is incredibly annoying.
I'd be incredibly grateful if this could be solved. :pray:

**Comment by kirill578** [comment]
if you are using home assistant you can create a webhook automation to relay the request via adb

```
alias: play youtube on tv
description: ""
trigger:
  - platform: webhook
    webhook_id: your-webhook-id-123
condition: []
action:
  - service: androidtv.adb_command
    data:
      command: >-
        am start -a android.intent.action.VIEW -d "{{ trigger.json.url }}" -n
        com.teamsmart.videomanager.tv/com.liskovsoft.smartyoutubetv2.tv.ui.main.SplashActivity
    target:
      entity_id: media_player.android_tv_192_168_1_253
mode: single
```
